// Code generated by sqlc-gen-ts-d1. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
//   sqlc-gen-ts-d1 v0.0.0-a@254c24db5bcb2e1e16559e7f8498d7fa673ada31

export type D1Migrations = {
  id: number;
  name: string | null;
  appliedAt: number | string;
};

export type SqliteSequence = {
  name: number | string | null;
  seq: number | string | null;
};

export type Problem = {
  id: string;
  title: string;
  content: string;
  difficulty: string;
  tests: string;
  playgroundUrl: string;
};

export type User = {
  userId: string;
  screenName: string;
};

export type Submission = {
  id: string;
  problemId: string;
  userId: string;
  code: string;
  codeLength: number | string;
  status: string;
  createdAt: string;
};

export type Judgement = {
  submissionId: string;
  status: string;
  diagnostics: string;
  createdAt: string | null;
};

export type ChallengeResult = {
  id: number;
  problemId: string;
  userId: string;
  status: string;
};

